"""empty message

Revision ID: 304a0b84eadb
Revises: 
Create Date: 2020-07-14 21:20:18.517595

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '304a0b84eadb'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('project',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=200), nullable=False),
    sa.Column('comments', sa.String(length=500), nullable=False),
    sa.Column('image_url', sa.String(length=200), nullable=True),
    sa.Column('image_public_id', sa.String(length=200), nullable=True),
    sa.Column('url_link', sa.String(length=200), nullable=True),
    sa.Column('github_link', sa.String(length=200), nullable=True),
    sa.Column('date_launched', sa.DateTime(), nullable=False),
    sa.Column('tags', sa.String(length=150), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('project')
    # ### end Alembic commands ###
